In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import nltk

In [2]:
!pip uninstall keras -y
!pip uninstall keras-nightly -y
!pip uninstall keras-Preprocessing -y
!pip uninstall keras-vis -y
!pip uninstall tensorflow -y

!pip install tensorflow==2.3.0
!pip install keras==2.4

Found existing installation: Keras 2.4.0
Uninstalling Keras-2.4.0:
  Successfully uninstalled Keras-2.4.0
Found existing installation: Keras-Preprocessing 1.1.2
Uninstalling Keras-Preprocessing-1.1.2:
  Successfully uninstalled Keras-Preprocessing-1.1.2
Found existing installation: tensorflow 2.3.0
Uninstalling tensorflow-2.3.0:
  Successfully uninstalled tensorflow-2.3.0
  Using cached tensorflow-2.3.0-cp38-cp38-manylinux2010_x86_64.whl (320.5 MB)
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
ERROR: tensorflow-gpu 2.2.0 has requirement tensorboard<2.3.0,>=2.2.0, but you'll have tensorboard 2.10.1 which is incompatible.
ERROR: tensorflow-gpu 2.2.0 has requirement tensorflow-estimator<2.3.0,>=2.2.0, but you'll have tensorflow-estimator 2.3.0 which is incompatible.
ERROR: tensorflow-cpu 2.2.0 has requirement tensorboard<2.3.0,>=2.2.0, but you'll have tensorboard 2.10.1 which is incompatible.
ERROR: tensorflow-cpu 2.2.0 has requirement tensorflow-estimator<2.3.0,>=

In [3]:
from tensorflow import keras
# !pip install tensorflow

2022-11-09 15:37:54.539465: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1


In [59]:
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
from keras.models import Sequential
from keras.layers import Dense
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split

In [5]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

In [6]:
ps = PorterStemmer()
wordnet=WordNetLemmatizer()
lemmatizer = WordNetLemmatizer()

In [7]:
df = pd.read_csv("pairs-label-training.csv")
df

text1  text2  label
0          98    651      0
1         696   1870      1
2        1073   1620      0
3         167    633      0
4           4    640      0
...       ...    ...    ...
155946    546   1512      1
155947    720   1902      1
155948   1112   1591      0
155949    396   1472      1
155950   1021   1680      0

[155951 rows x 3 columns]

In [8]:
file=open('text_and_id_sorted.txt','rU')
content = file.readlines()

/tmp/ipykernel_5330/148599554.py:1: DeprecationWarning: 'U' mode is deprecated
  file=open('text_and_id_sorted.txt','rU')


In [9]:
y = df['label']
X = df.drop('label',axis=1)

In [10]:
X

text1  text2
0          98    651
1         696   1870
2        1073   1620
3         167    633
4           4    640
...       ...    ...
155946    546   1512
155947    720   1902
155948   1112   1591
155949    396   1472
155950   1021   1680

[155951 rows x 2 columns]

In [11]:
  nltk.download()

NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------

Download which package (l=list; x=cancel)?
Packages:

Collections:

([*] marks installed packages)

Download which package (l=list; x=cancel)?
Packages:

Collections:

([*] marks installed packages)

Download which package (l=list; x=cancel)?

---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------

---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------

--------------------------------------------------------------------

    Error loading ll: Package 'll' not found in index


True

In [12]:
mother_corpus = []
for line in range(len(content)):
    mod_line=content[line]
    review = re.sub('[^a-zA-Z]', ' ', mod_line)
    review = review.lower()
    review = review.split()
    review = [lemmatizer.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    mother_corpus.append(review)
    

In [13]:
mother_corpus

['besides forest naturally developed forest man made forest developed artificially vast area land',
 'mother clean rice separating husk mud particle cooking',
 'free gift nature thing man cannot produce included land',
 'humanism concept man measure thing',
 'various design clothing found depending country time man woman person',
 'year men developed variety textile material brought new idea clothing',
 'noisy environment sleep baby hampered good health',
 'question superior profit farmer enclosure rather open field one case chain make change soil price like horse team must jog along rest',
 'according nimcock social scientist whole family organisation formed husband wife',
 'runner maintain body balance',
 'make proper purchasing policy accordance limited resource fulfilling basic requirement food clothing lodging etc family member',
 'thus gradually importance labour increased man needed capital cultivation setting factory increasing production',
 'others help',
 'among student teach

In [14]:
corpus = []
#content = file.readlines()
for row in range(len(X.index)):
    value1 = X.iat[row, 1]
    value2 = X.iat[row, 0]
    line1 = mother_corpus[value1-1]
    line2 = mother_corpus[value2-1]
    final_line=line1+' '+line2
    corpus.append(final_line)

In [15]:
# corpus

In [16]:
# Load, tokenize and process the data
import re                                                           #  Load the Regex-modul
with open('text_and_id_sorted.txt') as f:
    data = f.read()                                                 #  Read in the data
data = re.sub(r'[.,!?;-]', ' ',data)                                #  Punktuations are replaced by space
data = nltk.word_tokenize(data)                                     #  Tokenize string to words
data = [lemmatizer.lemmatize(word) for word in data if not word in set(stopwords.words('english'))]
data = [ ch.lower() for ch in data if ch.isalpha() or ch == '.']    #  Lower case and drop non-alphabetical tokens
print("Number of tokens:", len(data),'\n', data[:15])               #  print data sample

Number of tokens: 26441 
 ['besides', 'forest', 'naturally', 'developed', 'forest', 'man', 'made', 'forest', 'developed', 'artificially', 'vast', 'area', 'land', 'your', 'mother']


In [17]:
# Compute the frequency distribution of the words in the dataset (vocabulary)
fdist = nltk.FreqDist(word for word in data)
print("Size of vocabulary: ",len(fdist) )
print("Most frequent tokens: ",fdist.most_common(20) ) # print the 20 most frequent words and their freq.

Size of vocabulary:  6417
Most frequent tokens:  [('the', 435), ('man', 233), ('in', 145), ('one', 131), ('he', 116), ('water', 105), ('a', 101), ('men', 97), ('also', 95), ('plant', 95), ('time', 91), ('take', 91), ('make', 86), ('food', 86), ('it', 83), ('people', 81), ('if', 78), ('work', 76), ('different', 76), ('land', 71)]


In [18]:
from tensorflow.keras.preprocessing.text import one_hot

In [19]:
voc_size=6417

In [20]:
onehot_repr=[one_hot(words,voc_size)for words in mother_corpus] 
# print(onehot_repr)

In [21]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [22]:
import numpy as np

In [23]:
sent_length=1000
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 4680 1446 3143]
 [   0    0    0 ... 4316 6309 3019]
 [   0    0    0 ... 1152 2101 3143]
 ...
 [   0    0    0 ... 4143 3554 6356]
 [   0    0    0 ...  204  208  763]
 [   0    0    0 ...  740 1234 2307]]


In [24]:
embedded_docs.shape

(2000, 1000)

In [25]:
dim=10

In [26]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

2022-11-09 15:42:11.917863: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2022-11-09 15:42:12.203229: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0001:00:00.0 name: Tesla M60 computeCapability: 5.2
coreClock: 1.1775GHz coreCount: 16 deviceMemorySize: 7.94GiB deviceMemoryBandwidth: 149.31GiB/s
2022-11-09 15:42:12.203281: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2022-11-09 15:42:12.690778: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2022-11-09 15:42:13.159970: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2022-11-09 15:42:13.342238: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2022-1

In [27]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 1000, 10)          64170     
Total params: 64,170
Trainable params: 64,170
Non-trainable params: 0
_________________________________________________________________


In [28]:
  
# import tensorflow as tf

# tensor_1 = [.34, .45, .67, .65] 
# tensor_list = [[.34, .45, .67, .65], [.14, .35, .67, .65],
#             [.54, .95, .07, .5], [.64, .75, .81, .05], [.34, .45, .67, .65]]

# cosine_sim_values = tf.keras.losses.cosine_similarity(
#     tensor_1,
#     tensor_list,
#     axis=-1)

# print(cosine_sim_values.numpy())

In [29]:
print(model.predict(embedded_docs))

[[[-0.03739196 -0.01235484  0.0047575  ...  0.02520372 -0.00731073
   -0.01247605]
  [-0.03739196 -0.01235484  0.0047575  ...  0.02520372 -0.00731073
   -0.01247605]
  [-0.03739196 -0.01235484  0.0047575  ...  0.02520372 -0.00731073
   -0.01247605]
  ...
  [ 0.04183011  0.04530183  0.01607687 ...  0.02762076  0.02708218
   -0.00882758]
  [-0.0100712  -0.00176556  0.04868232 ...  0.02831152  0.02256439
   -0.04063465]
  [ 0.00821109  0.04372077  0.01673939 ...  0.04253025  0.01707036
    0.03332274]]

 [[-0.03739196 -0.01235484  0.0047575  ...  0.02520372 -0.00731073
   -0.01247605]
  [-0.03739196 -0.01235484  0.0047575  ...  0.02520372 -0.00731073
   -0.01247605]
  [-0.03739196 -0.01235484  0.0047575  ...  0.02520372 -0.00731073
   -0.01247605]
  ...
  [ 0.00661128 -0.00858301 -0.02029402 ...  0.01092354  0.04922071
    0.0241743 ]
  [-0.02691476  0.01143125 -0.00120429 ... -0.00801113 -0.04966495
    0.01459629]
  [ 0.01023021  0.03093855  0.04373151 ...  0.00459214 -0.0096889
    0.0

In [30]:
X_mother=model.predict(embedded_docs)

In [31]:
type(X_mother)

numpy.ndarray

In [32]:
len(X.index)

155951

In [33]:
X_new=[]
for row in range(len(X.index)):
    value1 = X.iat[row, 1]
    value2 = X.iat[row, 0]
    line1 = X_mother[value1-1]
    line2 = X_mother[value2-1]
    final_line=np.concatenate((line1,line2),axis=0)
    X_new.append(final_line)


In [34]:
X_arr=np.asarray(X_new)
X_arr.shape

(155951, 2000, 10)

In [36]:
# !pip install sklearn.cross_validation
from sklearn.model_selection import train_test_split

In [37]:
X_train_mega, X_test, y_train_mega, y_test = train_test_split(
X_arr,y , random_state=104,test_size=0.2, shuffle=True)

In [38]:
X_train, X_val, y_train, y_val = train_test_split(
X_train_mega,y_train_mega , random_state=104,test_size=0.25, shuffle=True)

In [39]:
from keras.layers import Activation, Dense

In [40]:
from keras.models import Sequential

In [41]:
from keras import Model
from keras.layers import Input, Dense, Bidirectional
from keras.layers.recurrent import LSTM




In [42]:
from keras.layers import SimpleRNN

In [61]:
model = keras.Sequential()

model.add(
    keras.layers.Bidirectional(keras.layers.LSTM(64, return_sequences=True), input_shape=(2000,10))
)
model.add(keras.layers.Bidirectional(keras.layers.LSTM(32)))
model.add(keras.layers.Dense(64, activation='relu'))
model.add(keras.layers.Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
bidirectional (Bidirectional (None, 2000, 128)         38400     
_________________________________________________________________
bidirectional_1 (Bidirection (None, 64)                41216     
_________________________________________________________________
dense_3 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 65        
Total params: 83,841
Trainable params: 83,841
Non-trainable params: 0
_________________________________________________________________


In [63]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [64]:
hist = model.fit(X_train, y_train,
          batch_size=32, epochs=5,
          validation_data=(X_val, y_val))

2022-11-09 15:55:46.719643: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 7485600000 exceeds 10% of free system memory.


Epoch 1/5
2925/2925 [==============================] - 4742s 2s/step - loss: 0.6922 - accuracy: 0.5166 - val_loss: 0.6930 - val_accuracy: 0.5156
Epoch 2/5
2925/2925 [==============================] - ETA: 0s - loss: 0.6927 - accuracy: 0.5157

In [ ]:
model.evaluate(X_test, y_test)#[1]